onlyBuiltDependencies:
  - esbuild
  - sharp
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
overrides:
  tinyclip: 0.1.12
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - astro@6.3.8
allowBuilds:
  esbuild: true
  sharp: true
